#!/usr/bin/env bash
# this program  prints "best school" 10 times
# At the 9th iteration, it prints "Hi"

i=1

while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
