#!/usr/bin/env bash
# this program  prints "best school" 10 times
# At the 9th iteration, it prints "Hi"



count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
